name: Run Orchestra Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  run-orchestra-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Run Orchestra Pipeline
        uses: orchestra-hq/run-pipeline@v1.2.0
        env:
          ORCHESTRA_ENV: "dev"
        with:
          api_key: ${{ secrets.ORCHESTRA_API_KEY }}
          pipeline_id: "ee110020-1ef6-4aba-bf01-026f63d33c82"
          run_inputs: |
            {
              "dbt_command": "run"
            }
